server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  compression:
    enabled: true
  tomcat:
    uri-encoding: UTF-8
    # max-http-form-post-size: 100MB
      
  # # https端口号.
  # port: 443
  # # 证书的路径.
  # ssl:
  #   key-store: classpath:keystore.p12
  # # 证书密码，请修改为您自己证书的密码.
  #   key-store-password: 2+2=Five
  # # 秘钥库类型
  #   keyStoreType: PKCS12
  # # 证书别名
  #   keyAlias: quickbuild

spring:
  profiles:
  # 激活相应的配置环境, 加入 application-mysql.yml
    # active: mysql
    active: mysql
  # 

  mvc:
    view:
      suffix: .html

  application:
    name: quick-build
    version: 2021.08.15-RELEASE

  output:
    ansi:
    # Color-coded Output
      enabled: detect

  servlet:
    multipart:
      # 单个文件的最大值, bind到CommonsMultipartResolver，请用字节数，1048576=1M，1073741824=1G
      max-file-size: 1073741824
      max-request-size: 1073741824

  #热部署生效
  devtools:
    restart:
      enabled: true

  ### jpa hibernate 配置
  jpa:
    open-in-view: true
    properties:
      hibernate:
        # dialect: org.hibernate.dialect.MySQLDialect
        # dialect: com.jhopesoft.framework.core.jdbc.support.sqlserver.SQLServerDialect
        # dialect: com.jhopesoft.framework.core.jdbc.support.oracle.OracleDialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        show_sql: false
        format_sql: false
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          provider_configuration_file_resource_path: ehcache.xml
  # cache:
  #   type: ehcache
  #   ehcache:
  #     config: classpath:ehcache.xml          
  activiti:
    database-schema-update: false
    check-process-definitions: false
    jpa-enabled: true
    #dataSource: dataSource
    #transactionManager: transactionManager
  ### 数据库连接设置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    # driver-class-name: 
    # url: 
    # username: 
    # password: 

    druid:
      # mysql sqlserver
      # validationQuery: SELECT 1
      # oracle
      # validationQuery: SELECT 1 FROM DUAL

      # 初始化连接池的和最小及最大个数
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      #配置一个连接在池中最小生存的时间，单位是毫秒，以下配置为5分钟，必须在规定时间内完成sql操作，否则就会被断开
      minEvictableIdleTimeMillis: 300000
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      useGlobalDataSourceStat: true
      #开通后可用 http://localhost:8081/druid/index.html来访问监控数据
      #spring监控，**.controller是我的控制层包名，也可以是服务层，用逗号分隔多个监控内容
      aop-patterns: com.jhopesoft.*.controller.*
      filters: stat,wall,slf4j
      statViewServlet:
        enabled: true
        #监控页面登录用户名
        loginUsername: admin
        ##监控页面登录密码
        loginPassword: admin

logging:
  file:
  # 超出指定大小(默认10M)后会生成指定文件xxx.log.2021-01-10.0.gz 的压缩文件
  # 当前的日志还是输出在指定的文件中。
    name: /Users/jfok/Desktop/logs/${server.servlet.context-path}-QBS-log.log
  pattern:
  # 设置日志中的日期属性：年二位、不要毫秒
    dateformat: yy-MM-dd HH:mm:ss
  level:
    root: warn
    # web group
    web: warn
    # sql group
    sql: warn
    '[org.hibernate.boot.internal.InFlightMetadataCollectorImpl]': error
    '[org.hibernate.orm.deprecation]': error
    '[com.jhopesoft]': warn
    '[org.springframework.test]': warn
    '[com.jhopesoft.framework.dao]': warn
    '[com.jhopesoft.framework.core.objectquery.generate]': warn
    '[com.alibaba.druid]': error
