package com.jhopesoft.framework.dao.entity.common;
// Generated 2022-03-22 09:43:31 by Quick build System

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicUpdate;

/**
 *
 * PubCountryCode(PubCountryCode) generated by Quick Build System
 *
 * 了解快速架构系统 https://github.com/jfok1972
 *
 * @author 蒋锋 jfok1972@qq.com
 *
 */

@Entity
@DynamicUpdate
@Table(name = "pub_country_code")
public class PubCountryCode implements Serializable {

	/** 国家地区编码 */
	private String countryCode;
	/** 中文名称 */
	private String chnName;
	/** 英文名称 */
	private String engName;

	public PubCountryCode() {
	}

	@Id

	@Column(name = "country_code_", unique = true, nullable = false, length = 3)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "chn_name_", nullable = false, length = 100)
	public String getChnName() {
		return this.chnName;
	}

	public void setChnName(String chnName) {
		this.chnName = chnName;
	}

	@Column(name = "eng_name_", nullable = false, length = 100)
	public String getEngName() {
		return this.engName;
	}

	public void setEngName(String engName) {
		this.engName = engName;
	}

}
