package com.jhopesoft.framework.dao.entity.common;
// Generated 2021-04-06 14:21:22 by Quick build System

import java.io.Serializable;
import java.sql.Timestamp;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;

/**
*
* PubDocumentfile(PubDocumentfile) generated by Quick Build System 
*
* 了解快速架构系统 https://github.com/jfok1972
*
* @author 蒋锋 jfok1972@qq.com
*
*/
@Entity
@DynamicUpdate
@SuppressWarnings("serial")
@Table(name = "pub_documentfile")
public class PubDocumentfile implements Serializable {

	/** 文档文件id */
	private String documentfileid;
	/** 文档文件编码 */
	private String filecode;
	/** 文档文件名称 */
	private String title;
	/** 分类 */
	private String filetype;
	/** 重要等级 */
	private int hintlevel;
	/** 发布机关 */
	private String publishorg;
	/** 文档文件内容 */
	private String context;
	/** 是否生效 */
	private boolean enabled;
	/** 发布时间 */
	private Timestamp startdate;
	/** 结束时间 */
	private Timestamp enddate;
	/** 备注 */
	private String remark;
	/** 创建者 */
	private String creater;
	/** 创建日期 */
	private Timestamp createdate;
	/** 最近修改者 */
	private String lastmodifier;
	/** 最近修改日期 */
	private Timestamp lastmodifydate;

	public PubDocumentfile() {
	}

	@Id
	/** 请使用 strategy = "uuid.hex" 主键中最好不要有“-”号 */
	@GeneratedValue(generator = "generator")
	@GenericGenerator(name = "generator", strategy = "uuid.hex")
	@Column(name = "documentfileid", unique = true, nullable = false, length = 40)
	public String getDocumentfileid() {
		return this.documentfileid;
	}

	public void setDocumentfileid(String documentfileid) {
		this.documentfileid = documentfileid;
	}

	@Column(name = "filecode", length = 50)
	public String getFilecode() {
		return this.filecode;
	}

	public void setFilecode(String filecode) {
		this.filecode = filecode;
	}

	@Column(name = "title", nullable = false, length = 50)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "filetype", length = 20)
	public String getFiletype() {
		return this.filetype;
	}

	public void setFiletype(String filetype) {
		this.filetype = filetype;
	}

	@Column(name = "hintlevel", nullable = false, length = 20)
	public int getHintlevel() {
		return this.hintlevel;
	}

	public void setHintlevel(int hintlevel) {
		this.hintlevel = hintlevel;
	}

	@Column(name = "publishorg", length = 50)
	public String getPublishorg() {
		return this.publishorg;
	}

	public void setPublishorg(String publishorg) {
		this.publishorg = publishorg;
	}

	@Column(name = "context", length = 5592405)
	public String getContext() {
		return this.context;
	}

	public void setContext(String context) {
		this.context = context;
	}

	@Column(name = "enabled", nullable = false)
	public boolean getEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@Column(name = "startdate", length = 19)
	public Timestamp getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Timestamp startdate) {
		this.startdate = startdate;
	}

	@Column(name = "enddate", length = 19)
	public Timestamp getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Timestamp enddate) {
		this.enddate = enddate;
	}

	@Column(name = "remark", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "creater", nullable = false, length = 40)
	public String getCreater() {
		return this.creater;
	}

	public void setCreater(String creater) {
		this.creater = creater;
	}

	@Column(name = "createdate", nullable = false, length = 19)
	public Timestamp getCreatedate() {
		return this.createdate;
	}

	public void setCreatedate(Timestamp createdate) {
		this.createdate = createdate;
	}

	@Column(name = "lastmodifier", length = 40)
	public String getLastmodifier() {
		return this.lastmodifier;
	}

	public void setLastmodifier(String lastmodifier) {
		this.lastmodifier = lastmodifier;
	}

	@Column(name = "lastmodifydate", length = 19)
	public Timestamp getLastmodifydate() {
		return this.lastmodifydate;
	}

	public void setLastmodifydate(Timestamp lastmodifydate) {
		this.lastmodifydate = lastmodifydate;
	}

}
