package com.jhopesoft.framework.dao.entity.common;
// Generated 2022-03-25 16:21:56 by Quick build System

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicUpdate;

/**
 *
 * 国民经济行业大类(PubIndustryClass) generated by Quick Build System 
 *
 * 了解快速架构系统 https://github.com/jfok1972
 *
 * @author 蒋锋 jfok1972@qq.com
 *
*/
@Entity
@DynamicUpdate
@Table(name = "pub_industry_class")
public class PubIndustryClass implements Serializable {

	/** 大类代码 */
	private String classId;
	/** 门类代码 */
	private PubIndustryCategory pubIndustryCategory;
	/** 行业大类名称 */
	private String className;

	public PubIndustryClass() {
	}

	@Id

	@Column(name = "class_id_", unique = true, nullable = false, length = 2)
	public String getClassId() {
		return this.classId;
	}

	public void setClassId(String classId) {
		this.classId = classId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "category_id_", nullable = false)
	public PubIndustryCategory getPubIndustryCategory() {
		return this.pubIndustryCategory;
	}

	public void setPubIndustryCategory(PubIndustryCategory pubIndustryCategory) {
		this.pubIndustryCategory = pubIndustryCategory;
	}

	@Column(name = "class_name_", nullable = false, length = 50)
	public String getClassName() {
		return this.className;
	}

	public void setClassName(String className) {
		this.className = className;
	}

}
