package com.jhopesoft.framework.dao.entity.common;
// Generated 2022-03-22 14:44:17 by Quick build System

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import org.hibernate.annotations.DynamicUpdate;

/**
 *
 * 行政区划(PubRegion) generated by Quick Build System 
 *
 * 了解快速架构系统 https://github.com/jfok1972
 *
 * @author 蒋锋 jfok1972@qq.com
 *
*/
@Entity
@DynamicUpdate
@Table(name = "pub_region")
public class PubRegion implements Serializable {

	/** 行政区划编码 */
	private String regionId;
	/** 行政区划名称 */
	private String name;

	public PubRegion() {
	}

	@Id

	@Column(name = "region_id_", unique = true, nullable = false, length = 6)
	public String getRegionId() {
		return this.regionId;
	}

	public void setRegionId(String regionId) {
		this.regionId = regionId;
	}

	@Column(name = "name_", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
